FROM golang:1.19.4-alpine3.17 as builder

WORKDIR /go/src

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" .

FROM alpine:3.14

RUN apk update && apk add postgresql-client 


WORKDIR /go/src

COPY --from=builder /go/src/GoDump /usr/bin/

EXPOSE 5600

ENTRYPOINT ["GoDump"]
